[project]
name = "search-authority"
authors = ["Web3 Innovation Labs"]
description = "Decentralized NFT Search and Discovery Platform"
telemetry = false
requirements = []
[contracts.search-authority]
path = "contracts/search-authority.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
